#!/bin/bash
#
# iperf2 iperf2 network bandwidth test
#
# chkconfig: 2345 80 30
# description: iperf2 network bandwidth test
# pidfile: /var/run/iperf2.pid
# Source function library.

. /etc/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

start() {
echo -n "Starting iperf2: "
/usr/bin/iperf2 -s -D >/dev/null 2>&1
touch /var/lock/subsys/iperf2
pidofproc iperf2 > /var/run/iperf2.pid
return 1
}

stop() {
echo -n "Shutting down iperf2: "
killproc iperf
rm -f /var/lock/subsys/iperf2
rm -f /var/run/iperf2.pid
return 1
}

case "$1" in
start)
start
;;
stop)
stop
;;
status)
status iperf2
;;
restart)
stop
start
;;
*)
echo "Usage: iperf2 {start|stop|status|restart}"
exit 1
;;
esac
exit $?
