#!/bin/bash
#
# iperfd iperf3 network bandwidth test
#
# chkconfig: 2345 80 30
# description: iperf3 network bandwidth test
# pidfile: /var/run/iperf3.pid
# Source function library.

. /etc/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

start() {
echo -n "Starting iperfd: "
/usr/bin/iperf3 -s -D >/dev/null 2>&1
touch /var/lock/subsys/iperf3
pidofproc iperf3 > /var/run/iperf3.pid
return 1
}

stop() {
echo -n "Shutting down iperf3: "
killproc iperf
rm -f /var/lock/subsys/iperf3
rm -f /var/run/iperf3.pid
return 1
}

case "$1" in
start)
start
;;
stop)
stop
;;
status)
status iperf3
;;
restart)
stop
start
;;
*)
echo "Usage: iperf3 {start|stop|status|restart}"
exit 1
;;
esac
exit $?
